name: .NET

on:
  pull_request:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: da-bot
    - name: Build
      run: dotnet build --no-restore
      working-directory: da-bot
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: da-bot
